### ISSUE TITLE
"Link text unclear" should detect image links as image links

### ISSUE THREAD

**Issue by kevinb7** [Khan/tota11y#1]
Right now it comes up with the following message for the image link on the gh-pages.
```
The text " " is unclear without context
and may be confusing to screen readers. Consider
rearranging the <a></a> tags or
including special screen reader text.
```
It would be nice if it said something like:
```
You have an image link without alt text.  Please add an alt attribute to the img tag.
```

**Comment by jdan** [comment]
This is an outstanding bug for Accessibility Developer Tools. https://github.com/GoogleChrome/accessibility-developer-tools/issues/156

We can remedy it by adding an extra check for getTextFromDescendantContent until they fix, though :)

**Comment by kevinb7** [comment]
I didn't realize it was a bug b/c when I was looking at it before you added alt text to the image on gh-pages.  In addition to fixing the bug, I was thinking it would be nice to have an error message that calls out that's it's an image link issue.  It's really a nice to have.  Since I'm interested in it, I'll look into and send you pull request when I have some time.

**Comment by jdan** [comment]
> I was thinking it would be nice to have an error message that calls out that's it's an image link issue

Great idea, I imagine this is a common use-case.
