### ISSUE TITLE
tota11y button overlayed by site content

### ISSUE THREAD

**Issue by Ryuno-Ki** [Khan/tota11y#104]
I've tested the Bookmarklet today at our production website https://de.induux.com/

Since we have a Cookie hint as bar at the bottom, the glasses button was not visible (overlayed by the bar).
Can you detect, whether the position you want to place the glasses button is already used by content elements? Otherwise it would be handy to have the button displayed somewhere else.
What about on the right/left of the page at about 1/3 of the height?

**Comment by jdan** [comment]
Hey @Ryuno-Ki,

Sorry you hit this! Unfortunately we're always going to find ourselves in an edge case like this, so in the past I've recommended adding some custom CSS to move the toolbar. Check out https://github.com/Khan/tota11y/issues/98#issuecomment-240711472 for one proposed solution. It's not pretty, but it works. Does that suffice?

**Comment by Ryuno-Ki** [comment]
How would I test that?
From what I've read the bookmarklet creates a `<script>` and loads code by adding that to the DOM.

So I assume, I'd need to fork the project and modify the code and then drag&drop another bookmarklet into the bookmark bar?

**Comment by jdan** [comment]
The CSS I linked above would be placed on the website you're testing, not in tota11y's source code. Does that make sense?

**Comment by Ryuno-Ki** [comment]
Feels meh. I'm looking whether I csn figure out a better solution.

**Comment by Ryuno-Ki** [comment]
On StackOverflow I [discovered](http://stackoverflow.com/a/9915546)  `document.elementFromPoint()`, which [browser support looks great](http://caniuse.com/#search=elementfrompoint).

I'll try [that API](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) on my fork and let you know my findings, @jdan!
