### ISSUE TITLE
Uncaught Type errors; specific sites

### ISSUE THREAD

**Issue by jasonday** [Khan/tota11y#105]
Receiving Uncaught Type errors on specific sites, presumably due to conflicts. 

> tota11y.min.js:40 Uncaught TypeError: Cannot read property 'properties' of undefined

> tota11y.min.js:40 Uncaught TypeError: Cannot read property 'AuditConfiguration' of undefined

The functionality of the plugin on the site (llbean.com), is that the landmarks and headings work as expected, but the alt-text, labels, link text, contrast, and the screenreader wand do not work and show console errors. 

Please let me know if there's additional context/information I can provide.

**Comment by jdan** [comment]
Heya @jasonday,

Thank you for reporting, and sorry you ran into this. Unfortunately it looks like #85 is biting us again :( I'm going to close this in favor of that issue, but will bump priority accordingly.
