### ISSUE TITLE
Add update to NPM for auto update to CDNs?

### ISSUE THREAD

**Issue by MattSnowOregonGov** [Khan/tota11y#106]
Hey Jordan!

Would you mind adding the 0.1.6 release to the npm auto update source (https://www.npmjs.com/package/tota11y)? CDNJS isn't getting your fantastical updates. 

Peter Dave Hello͌ͯͦ̉ manually updated CDNJS for me, but it'd be awesome if it could update automatically! 

BTW, the State of Oregon web content managers say thank you!!

Thanks!
Matt

**Comment by jdan** [comment]
Eek, sorry about that! Just went ahead and published 0.1.6. Let me know if you're still having troubles.

**Comment by MattSnowOregonGov** [comment]
Looks like jsDelivr got 0.1.6. I would conjecture that the issue is resolved. Thanks!!
