### ISSUE TITLE
Unclear what WCAG level of compliance tota11y can help with

### ISSUE THREAD

**Issue by timrhaynes** [Khan/tota11y#112]
I haven't dug through the code or researched this 100% exhaustively. However, it's not clear to me what level of WCAG compliance tota11y can help achieve. Can I use it for 2.0 AA level, for instance?

**Comment by jdan** [comment]
@timrhaynes There is no 1:1 mapping to any level of compliance, unfortunately. But a few of tota11y's plugins, like alt-text and contrast can help you get there.

**Comment by jdan** [comment]
Going to close this for now, but please holler if you have any further questions!

**Comment by Ryuno-Ki** [comment]
According to an article on UK HomeOffice accessibility blog about [what they found when they tested tools on the world's least accessible webpage](https://accessibility.blog.gov.uk/2017/02/24/what-we-found-when-we-tested-tools-on-the-worlds-least-accessible-webpage/) you should not rely on tooling.
Their case study showed that it catches ~30% of issues.
