### ISSUE TITLE
Could this be modified or added into a browser plugin?

### ISSUE THREAD

**Issue by mejackreed** [Khan/tota11y#14]
Great job with this, wondering if there are plans for a browser plugin?

I would be happy to work on one to help out.

**Comment by jdan** [comment]
We'll probably stick with the bookmarklet for now (http://khan.github.io/tota11y/#Installation). A browser extension would open the doors for more interesting tests, but I would be hesitant to make some features missing from the original script. Plus I don't want to manage a bunch of extensions in the near future.

Not an impossibility though, what are your thoughts?

**Comment by mejackreed** [comment]
Ah missed the bookmarklet installation instructions! Thanks for that... I think thats fine for now.

**Comment by jdan** [comment]
I'm planning on moving a couple things up near the top of the page - namely a link to GitHub and the bookmarklet. Sorry you missed it!
