### ISSUE TITLE
Port to axe-core

### ISSUE THREAD

**Issue by dylanb** [Khan/tota11y#16]
I have ported your project to the axe-core library. You can find it here.

https://github.com/dylanb/tota11y

There are some significant differences including:

1. does not support the color contrast suggestion - this could be included by combining the accessibility chrome dev tools as well as axe, or by implementing a function to replicate that
2. I fixed the ARIA landmarks code to work with HTML5 elements and only include the real landmark roles
3. I added an "aXe" category, which runs all the axe-core rules and displays generic information with these issues

The axe-core library includes a bunch more rules that the Google library and has support for all the ARIA labelling techniques, so the image rule now supports aria-label, aria-labelledby etc.

There are some other minor differences and I also uncovered a bug in axe-core related to role="presentation" on images...

I would submit it as a PR but I am not sure you are interested in using the axe-core library (instead-of or in addition to the Google library), if you are, I will go ahead an submit the PR, I am also open to collaborating on making the integration as kick-ass as possible.

**Comment by jdan** [comment]
Hey Dylan! Just poking around your repo, very cool stuff - hope you had fun hacking on it.

I'm unlikely to switch to aXe just because Accessibility DevTools has been so good to us, but I'd love to see your landmarks and img labeling fixes make their way upstream.

I'll close this issue for now, but would love to continue any discussion here.

**Comment by dylanb** [comment]
I could submit the landmarks changes because they are independent of the axe-core library the image changes are dependent on it though.

I actually think you should consider using both libraries. There is a little overlap between the two but what we provide is much more comprehensive.

**Comment by jdan** [comment]
I'm going to be adding a few more features very soon (got a test for unsemantic buttons landing in the next few days), so I'll be sure to check more axe-core (the docs are really great by the way) and see if it makes sense to include it.

Awesome work, thanks for contributing it to the community :)
