### ISSUE TITLE
Bookmarklet -"TypeError: Cannot read property 'trim' of null" for Link Text and Labels tools

### ISSUE THREAD

**Issue by redking** [Khan/tota11y#23]
Hey,

I'm having an issue with the bookmarklet when using the Link Text and Labels tools. When I click on either, I see the following error in the console

`Uncaught TypeError: Cannot read property 'trim' of null`

arising from this line of code 

 `return "" === axs.properties.findTextAlternatives(a, {}).trim() ? !1 : !0;`

The expression `axs.properties.findTextAlternatives(a, {})` is returning `null`.

I see this error on a number of sites - Gmail, for example. Curiously enough, both tools work fine when I test on http://khan.github.io/tota11y/

I'm using the latest version of Chrome.

**Comment by jdan** [comment]
Thanks for reporting @redking. I've seen this issue myself a few times - looks like [a bug upstream in Accessibility Developer Tools](https://github.com/GoogleChrome/accessibility-developer-tools/pull/150).

We could probably change how we consume their API, though, in the meantime.

**Comment by jdan** [comment]
Fix coming soon upstream. https://github.com/GoogleChrome/accessibility-developer-tools/pull/188

**Comment by jdan** [comment]
This is fixed and landed on master. Will close this once I put up a new build!

**Comment by jdan** [comment]
@redking Just pushed out a new version of tota11y, powered by a newer version of Accessibility Developer Tools. This issue seems fixed, but please let me know if you see it again!
