### ISSUE TITLE
Image alt text shows 45 + the actual number of errors

### ISSUE THREAD

**Issue by ahallicks** [Khan/tota11y#27]
When using this awesome bookmarklet, even on your site, the alt text test always shows at least 45 errors. It seems to add any real errors to that amount.

For example, on http://khan.github.io/tota11y/#Try-it it says 46 when I can only actually find one error in your test area.
![tota11y](https://cloud.githubusercontent.com/assets/717299/8412185/09fc7d10-1e80-11e5-9152-a891c166fd82.jpg)

**Comment by jdan** [comment]
That is *remarkably* interesting. I'm unable to reproduce the error in my browser collection, can you link to another site with this issue?

I'm wondering if there are some rogue browser extensions inserting pixels in your browser...

**Comment by ahallicks** [comment]
Ah! Yes. Actually, I think it's coming from an extension I wrote myself that inserts some images that tell you where a link is going. I should probably add some alt attributes to those! ;-)

Good spot!

**Comment by jdan** [comment]
Cool glad we were able to find it :) It's a shame there's no easy way to see violating code from the error messages - hoping to fix that in #18
