### ISSUE TITLE
unable to copy and paste from error description

### ISSUE THREAD

**Issue by jmhodges** [Khan/tota11y#28]
When selecting an error type, the window that opens up on the right that describes the error and proposes a fix has text that can't be selected for copy and paste. It will be really nice to let folks copy and paste from there. 

For instance, I was trying to see what the new colors it proposes looks like and had to go back and forth from browser to the DevTool style tool or my text editor when I'd really like to just copy and paste it in.

**Comment by jdan** [comment]
Forgot to make an issue for this - thank you!

Yeah the whole error, text included, is a trigger. I think we can get by just fine by making only the title trigger an expand/collapse.

**Comment by jgardella** [comment]
Fixed in #40.

**Comment by jmhodges** [comment]
Thank you!

**Comment by jdan** [comment]
Closed via #40. Go @jgardella!
