### ISSUE TITLE
Some functionality broken in Firefox

### ISSUE THREAD

**Issue by simevidas** [Khan/tota11y#32]
Could you test the bookmarklet in Firefox? For me, the following controls do not work:

* Contrast
* Link text
* Labels

and these errors appear in the console:

![capture](https://cloud.githubusercontent.com/assets/716405/8447745/dd507250-1fbd-11e5-8ef2-ce10f6972a71.PNG)

**Comment by profan** [comment]
Seconded, Firefox 38.0 on Linux here.

Though only having problems with the Contrast control, the Link text and Labels seem to be working.

**Comment by jdan** [comment]
Yep, I can confirm this one. It's failing to compute the background color for some elements - will investigate.

**Comment by SteveALee** [comment]
+1 Contrast fails on the demo for me in latest FIrefox on windows

**Comment by jdan** [comment]
Might be prevalent in IE11 as well based on twitter feedback. I'll dive in today.

**Comment by SteveALee** [comment]
enjoy! :)



Steve Lee
OpenDirective http://opendirective.com

**Comment by jdan** [comment]
Okay I'm going to begin opening up separate issues and tracking them there. We've got a few separate issues. Not closing this right away.

**Comment by jdan** [comment]
@simevidas Hey Sam, mind showing me an example for the link text and labels plugins failing? I suspect that it's not a Firefox issue but something along the lines of #35.

Contrast is definitely FF, though, and I've got #37 to track it.

**Comment by simevidas** [comment]
@jdan Link text and Labels works now in Firefox/Windows for me. 😄 (I had to re-install the bookmarklet. )

**Comment by jdan** [comment]
@simevidas not 100% on what changed, but if it pops up again and isn't related to #35 let me know :)

Going to close this now in favor of #37. Thanks again for reporting.

**Comment by jdan** [comment]
9ccac407f06c509d21ada463dac30a71d5d0c52d has the contrast fix for those curious :)
