### ISSUE TITLE
Add build/ folder in .gitignore file

### ISSUE THREAD

**Issue by ankitaggarwal011** [Khan/tota11y#39]
Hi @jdan ,

Please add build/ folder in gitignore. Since changing/updating code requires rebuilding from source again to test the output, this proves to be a pain when the changes has to be pushed to the master and this possibly results in conflicts.

Thanks!

**Comment by jdan** [comment]
This is checked in to prevent a build step after fetching tota11y. This is how we use it on the `gh-pages` branch.

You'll notice that jQuery, Accessibility Developer Tools, and a number of other JavaScript libraries check in their `build/`/`dist/` directory.

If you need help fixing a merge conflict feel free to comment here.

**Comment by ankitaggarwal011** [comment]
I understand. I wasn't aware about this. It was just a little inconvenient to resolve merge conflicts everytime a change happens, but it's nothing that couldn't be solved. Now, I have setup a different branch/project for testing. Thanks!
