### ISSUE TITLE
Character font for go to issue is missing

### ISSUE THREAD

**Issue by snorrekim** [Khan/tota11y#4]
![image](https://cloud.githubusercontent.com/assets/5329330/8059755/ee9fac68-0ec1-11e5-84be-d5b52f33d8a1.png)

Tested on Windows. Firefox, Chrome, IE10

Looks like you were going for [this character](http://www.fileformat.info/info/unicode/char/26b2/index.htm)

**Comment by jdan** [comment]
Ah, sad to see this character isn't showing up :( Looks like I'll need to use some SVG or draw it with CSS.

Thanks for pointing this out.

**Comment by snorrekim** [comment]
Some hover effects would be nice, as it is I had no way of knowing that icon would do a different thing than clicking on the text for slide-down right next to it. I know the icon wasn't a square when I first tried it, but it took me some time to actually figure out that you could click it. And that was only because I kept thinking "of course they've added that functionality! It must be here somewhere."

Maybe add  ```title="Go to issue"``` as well so that text appears on mouseover?

**Comment by jdan** [comment]
`:hover/:focus` and a title sounds good to me. If I can get to this today I'll include those things.
