### ISSUE TITLE
Annotation toggling

### ISSUE THREAD

**Issue by jgardella** [Khan/tota11y#49]
After implementing the contrast suggestion preview, I think it might be useful to have a way to toggle annotations on and off. For smaller elements, the annotation can completely cover the element, which can be inconvenient generally speaking, but also makes it impossible to preview the suggested colors, and could prove obstructing in future plugins.

**Comment by jdan** [comment]
Fixed via #52.

FWIW I guess "Fixes" needs to be in the commit message to auto-close, not the PR title.
