### ISSUE TITLE
CSS height of children should be neutralised

### ISSUE THREAD

**Issue by vasilisvg** [Khan/tota11y#7]
If the host page uses something like `height: 100vh` the panel becomes unusable. This can be solved by adding `height: auto !important;` to the `.tota11y *` block.
[Here’s a page](https://vasilis.nl/random/daily/rectangle/?i=1433833274-98-96-47-97-11-68-242-162.svg) that uses `height: 100vh;`

**Comment by jdan** [comment]
Thanks for finding this, making comprehensive reset styles has proven to be super tricky.

I'll get a fix up for the height issue, but I don't think I'll be aiming to fix the background colors getting mixed up on that page. I need dynamic background colors for the color swatches, so unfortunately I can't do a `background: none` reset.
