### ISSUE TITLE
Is it possible to get a non-minified file?

### ISSUE THREAD

**Issue by snorrekim** [Khan/tota11y#8]
Although good for production code, a minified file is not much help for development and debugging. Is it possible to have both a minified, and a non minified version of the file? It would help greatly when reporting bugs and suggestions.

**Comment by akkatracker** [comment]
Yep agree with this. A non minified file makes sense. 

In case your were itching his a "de minified" version: https://gist.githubusercontent.com/akkatracker/1db35a2ea63013fa1a26/raw/07dc1031e8da8ec62348e32e4822660be33ec7e5/gistfile1.txt

**Comment by jdan** [comment]
While developing with webpack-dev-server (using `npm test`), you'll be served unminified code.

![image](https://cloud.githubusercontent.com/assets/287268/8083253/41899cb0-0f51-11e5-94e7-a0648c068b25.png)

Does this help?

**Comment by snorrekim** [comment]
I certainly does, it's possible for me to just use this file. 

But, for anyone who isn't really ready or able to use the source to build it themselves, there should really be an easily available tota11y.min.js and tota11y.js file. Both on the [release page](https://github.com/Khan/tota11y/releases/tag/0.0.3) and in the /build folder.

Though, with it available on the webpack-dev-server test page it's not necessarily a pressing issue. But it would help a lot with ease of use for a lot of people. No need to set up Node, or webpack or use a single command line to get started with looking at the code. Just download a js file and put it in a page.

Also, it makes it easier to compare the different versions. Because most people will just be using the final file. And it's daunting to upgrade version on a file you can't even read.

**Comment by jdan** [comment]
:+1: @snorrekim that all makes perfect sense to me. Happy to build both a minified and non-minified. I'm still pretty new to webpack configs but I can try to figure this out when I have the time unless someone beats me to it.

**Comment by jdan** [comment]
Closed via #26.

This is already making the debugging experience more pleasant for me, but unfortunately we use `script-loader` to load in Accessibility DevTools, which just takes the source code and makes it into a string :( So unfortunately debugging *that* will still be tricky.
