### ISSUE TITLE
Issue with tota11y and webpack

### ISSUE THREAD

**Issue by fephil** [Khan/tota11y#84]
Hi,

I'm getting the following error when trying to require tota11y with a webpack build:

ERROR in ./~/tota11y/index.js
Module parse failed: /[...]/node_modules/tota11y/index.js Line 53: Unexpected token <
You may need an appropriate loader to handle this file type.
|         let $defaultPlugins = plugins.default.map((Plugin) => { // eslint-disable-line no-unused-vars
|             // Render each plugin with the bound click handler
|             return <Plugin onClick={::this.handlePluginClick} />;
|         });

I'll try and investigate this more but I wanted to post here incase there is something obvious I'm doing wrong.

**Comment by jdan** [comment]
Hey @PJL101,

Thanks for bringing this to my attention. Can you explain how you're requiring tota11y in your project? tota11y doesn't export anything, so you'll need to use with webpack's `script-loader` [like we do for Accessibility Developer Tools](https://github.com/Khan/tota11y/blob/master/index.js#L15-L16).

That means your code should have something like:

```
require("script!./node_modules/tota11y/build/tota11y.min.js")
```

once to invoke the tota11y script globally. This will mount it to the body.

I'm also curious to hear more about your project! Is this a dev-specific webpack config? Tota11y is quite large (~252kB minified) so I wouldn't recommend serving it to any users.

**Comment by jdan** [comment]
I appreciate you bringing this up, though, this might be a pretty common pattern that we should do a better job of documenting.

**Comment by PJL101** [comment]
Hi @jdan,

In short, I have completely got it wrong in terms of how to require tota11y. I was just doing a standard require. I'll try this out ASAP and reply. I'd be happy to do a PR to add the instruction to the readme file.

Also, I still believe there is an issue with npm installing the wrong version (0.1.0).

**Comment by PJL101** [comment]
In relation to a 'dev' workflow, I haven't quite thought this out yet but I might do it as part of a gulp task. It's for my [boilerplate](http://github.com/PJL101/foley).

**Comment by jdan** [comment]
> In short, I have completely got it wrong in terms of how to require tota11y.

Not at all, we definitely don't make this very clear :)

> Also, I still believe there is an issue with npm installing the wrong version (0.1.0).

Yes I definitely need to publish the latest build.

Very excited to see it in a boilerplate! I'll check back with you later tonight to make any changes to the README. Feel free to beat me to it with a PR - and thanks again!

**Comment by PJL101** [comment]
Sorry @jdan I haven't forgotten this. I have got some time tomorrow to test this and PR a doc change.

**Comment by jdan** [comment]
@PJL101 ha, me too :) I went ahead and published a v0.1.3 build.

**Comment by fephil** [comment]
@jdan I haven't forgotten about this! I'm currently working on how best to integrate this into the boilerplate. I'll update when it's in and working

**Comment by fephil** [comment]
Hi @jdan.

So it's been quite a bit longer then I would have liked(!) but my workflow now has tota11y integration. I ended up not using webpack and adding tota11y in a special 'gulp audit a11y' task.

https://github.com/fephil/garrus
